imports:
  - { resource: ./controllers/application.yaml }
  - { resource: ./shared/application.yaml }
  - { resource: ./users/application.yaml }
  - { resource: ./owners/application.yaml }
  - { resource: ./properties/application.yaml }
