imports:
  - { resource: ./application.yaml }

services:

  Shared.EnvironmentArranger:
    class: ../../../../../tests/modules/shared/infrastructure/typeorm/typeOrmEnvironmentArranger
    arguments: ['@Shared.ConnectionManager']
