services:
  postgres-db:
    image: postgres:17.6
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - catabe-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  postgres-db-test:
    image: postgres:17.6
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - catabe-postgres-data-test:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  catabe-postgres-data:
  catabe-postgres-data-test:
