services:

  Controllers.status.StatusGetController:
    class: ../../../status/statusGetController
    arguments: []

  Controllers.users.UserPutController:
    class: ../../../users/userPutController
    arguments: ['@Users.application.UserRegistrar']

  Controllers.users.UserGetController:
    class: ../../../users/userGetController
    arguments: ['@Users.application.UserFinder']

  Controllers.users.UserPostAuthController:
    class: ../../../users/userPostAuthController
    arguments: ['@Users.application.UserAuthenticator', '@Users.domain.UserTokenSigner']

  Controllers.owners.OwnerPutController:
    class: ../../../owners/ownerPutController
    arguments: ['@Owners.application.OwnerUpdater']

  Controllers.owners.OwnerGetController:
    class: ../../../owners/ownerGetController
    arguments: ['@Owners.application.OwnerFinder']

  Controllers.owners.OwnerGetAllController:
    class: ../../../owners/ownerGetAllController
    arguments: ['@Owners.application.OwnersFinder']

  Controllers.owners.OwnerDeleteController:
    class: ../../../owners/ownerDeleteController
    arguments: ['@Owners.application.OwnerDeleter']

  Controllers.properties.PropertyPutController:
    class: ../../../properties/propertyPutController
    arguments: ['@Properties.application.PropertyUpdater', '@Properties.application.PropertyCreator', '@Properties.application.PropertyFinder']

  Controllers.properties.PropertyGetController:
    class: ../../../properties/propertyGetController
    arguments: ['@Properties.application.PropertyFinder']

  Controllers.properties.PropertiesGetAllController:
    class: ../../../properties/propertiesGetAllController
    arguments: ['@Properties.application.PropertiesFinder']

  Controllers.properties.PropertyDeleteController:
    class: ../../../properties/propertyDeleteController
    arguments: ['@Properties.application.PropertyDeleter']

