services:

  Properties.domain.PropertyRepository:
    class: ../../../../modules/properties/infrastructure/persistence/typeOrmPropertyRepository
    arguments: ['@Shared.ConnectionManager']

  Properties.application.PropertyUpdater:
    class: ../../../../modules/properties/application/propertyUpdater
    arguments: ['@Properties.domain.PropertyRepository']

  Properties.application.PropertyFinder:
    class: ../../../../modules/properties/application/propertyFinder
    arguments: ['@Properties.domain.PropertyRepository']

  Properties.application.PropertiesFinder:
    class: ../../../../modules/properties/application/propertiesFinder
    arguments: ['@Properties.domain.PropertyRepository']

  Properties.application.PropertyDeleter:
    class: ../../../../modules/properties/application/propertyDeleter
    arguments: ['@Properties.domain.PropertyRepository']

  Properties.application.PropertyCreator:
    class: ../../../../modules/properties/application/propertyCreator
    arguments: ['@Properties.domain.PropertyRepository']

  PropertiesOwners.domain.PropertyOwnerLinkRepository:
    class: ../../../../modules/propertiesOwners/infrastructure/persistence/typeOrmPropertyOwnerLinkRepository
    arguments: ['@Shared.ConnectionManager']

  PropertiesOwners.application.PropertyOwnersAdder:
    class: ../../../../modules/propertiesOwners/application/propertyOwnersAdder
    arguments: ['@PropertiesOwners.domain.PropertyOwnerLinkRepository']

  PropertiesOwners.application.PropertyOwnersRemover:
    class: ../../../../modules/propertiesOwners/application/propertyOwnersRemover
    arguments: ['@PropertiesOwners.domain.PropertyOwnerLinkRepository']

  PropertiesOwners.application.PropertyOwnersFinder:
    class: ../../../../modules/propertiesOwners/application/propertyOwnersFinder
    arguments: ['@PropertiesOwners.domain.PropertyOwnerLinkRepository', '@Owners.domain.OwnerRepository']

  PropertiesOwners.application.OwnerPropertiesFinder:
    class: ../../../../modules/propertiesOwners/application/ownerPropertiesFinder
    arguments: ['@PropertiesOwners.domain.PropertyOwnerLinkRepository', '@Properties.domain.PropertyRepository']
